import type { AppData, AuditReport, VarianceRecord } from "../types";
import {
  findHighestVarianceEmployee,
  findHighestVarianceShift,
} from "../analysis/investigator";

export function generateAuditReportForOutlet(
  data: AppData,
  variances: VarianceRecord[],
  outletId: string
): AuditReport {
  const now = new Date();
  const weekEnd = new Date(now);
  const weekStart = new Date(now);
  weekStart.setDate(weekStart.getDate() - 6);

  const outletVariances = variances.filter(
    (v) => v.outletId === outletId && v.variance < 0
  );
  const inventoryLoss = outletVariances.reduce((s, v) => s + v.lossValue, 0);

  const topMissingProducts = [...outletVariances]
    .sort((a, b) => b.lossValue - a.lossValue)
    .slice(0, 5)
    .map((v) => ({
      name: v.itemName,
      variance: v.variance,
      lossValue: v.lossValue,
    }));

  const outletEvents = data.events.filter((e) => e.outletId === outletId);
  const outletEmployees = data.employees.filter((e) => e.outletId === outletId);

  const outletA = data.outlets[0];
  const outletB = data.outlets[1];
  const lossA = variances
    .filter((v) => v.outletId === outletA?.id && v.variance < 0)
    .reduce((s, v) => s + Math.abs(v.variance), 0);
  const lossB = variances
    .filter((v) => v.outletId === outletB?.id && v.variance < 0)
    .reduce((s, v) => s + Math.abs(v.variance), 0);
  const stockA = data.inventory
    .filter((i) => i.outletId === outletA?.id)
    .reduce((s, i) => s + i.currentStock, 0);
  const stockB = data.inventory
    .filter((i) => i.outletId === outletB?.id)
    .reduce((s, i) => s + i.currentStock, 0);

  return {
    id: `audit-${outletId}-${Date.now()}`,
    weekStart,
    weekEnd,
    outletId,
    inventoryLoss,
    topMissingProducts,
    highestVarianceShift: findHighestVarianceShift(outletEvents),
    highestVarianceEmployee: findHighestVarianceEmployee(outletEvents, outletEmployees),
    outletComparison:
      outletA && outletB
        ? {
            outletA: {
              name: outletA.name,
              lossPercent: stockA > 0 ? (lossA / stockA) * 100 : 0,
            },
            outletB: {
              name: outletB.name,
              lossPercent: stockB > 0 ? (lossB / stockB) * 100 : 0,
            },
          }
        : undefined,
  };
}

export function buildAuditPrintHtml(report: AuditReport, outletName: string): string {
  const rows = report.topMissingProducts
    .map(
      (p, i) =>
        `<tr><td>${i + 1}</td><td>${p.name}</td><td>${p.variance}</td><td>₹${p.lossValue.toLocaleString("en-IN")}</td></tr>`
    )
    .join("");

  return `<!DOCTYPE html><html><head><title>BarIQ Audit Report</title>
<style>body{font-family:system-ui,sans-serif;padding:40px;color:#111}h1{font-size:24px}table{width:100%;border-collapse:collapse;margin-top:16px}th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f5f5f5}.metric{font-size:28px;font-weight:bold;color:#dc2626;margin:8px 0}</style>
</head><body>
<h1>BarIQ Weekly Audit Report</h1>
<p><strong>Outlet:</strong> ${outletName}</p>
<p><strong>Period:</strong> ${report.weekStart.toLocaleDateString()} — ${report.weekEnd.toLocaleDateString()}</p>
<h2>Inventory Loss</h2>
<p class="metric">₹${report.inventoryLoss.toLocaleString("en-IN")}</p>
<h2>Top Missing Products</h2>
<table><thead><tr><th>#</th><th>Product</th><th>Variance</th><th>Loss</th></tr></thead><tbody>${rows}</tbody></table>
<h2>Highest Variance Shift</h2><p>${report.highestVarianceShift}</p>
<h2>Highest Variance Employee</h2><p>${report.highestVarianceEmployee.name} (${report.highestVarianceEmployee.employeeCode})</p>
${report.outletComparison ? `<h2>Outlet Comparison</h2><p>${report.outletComparison.outletA.name}: ${report.outletComparison.outletA.lossPercent.toFixed(1)}% loss</p><p>${report.outletComparison.outletB.name}: ${report.outletComparison.outletB.lossPercent.toFixed(1)}% loss</p>` : ""}
<p style="margin-top:40px;font-size:12px;color:#666">Generated by BarIQ Inventory Intelligence Platform</p>
</body></html>`;
}

export function exportAuditToPdf(report: AuditReport, outletName: string) {
  const html = buildAuditPrintHtml(report, outletName);
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 300);
}
